#!/bin/bash
#first set the python executable path as well as the project (repository) folder
export PATH=/mnt/c/Users/Richard/Anaconda3/:%PATH:/mnt/d/Work/projects/MSI/subspaceMSI_py/CS-FTMSI
out_dir="coronal_40perc" #where the output files will be stored in the output folder.
path_files="./file_dir_coronal_sparse.json" #file that indicates the required data paths
ROI="R00" #ROI header for the data imaging file.
basis_ROI="R00" #ROI header for the basis imaging file.
get_data_basis="False" #if to prepare data for the basis estimation. set to True will require .ser file to sample the long transients for basis estimation.
estimate_basis="False" #set to True to estimate the basis transients if no predefined basis file is available.

#if both get_data_basis and estimate_basis are False, then the program will look for basis transients file in the output folder.
basis_path="./output/coronal_40perc/basis_transients.npy" 
tissue_autoxcute_path="./Imaging_20210419_Coronal_sparse0.4.xml" #autoxcute file generated by Bruker.
sample_autoxcute_path="./sampled_Imaging_20210419_Coronal_sparse0.4.xml" #sampled autoxcute file for acquisition.
n_basis_data=4000 #number of transients loaded for the basis estimation. only if get_data_basis and estimate_basis set to True.
lamb="0.1" #lambda parameter for ADMM.
mu="1e-4" #mu parameter for ADMM.
max_iter=50 #maximum number of iteration for the optimization algorithm.
r=100 #number of basis transients used for reconstruction.
mz_range="400 1000" #m/z range for the data processing.

python.exe create_data.py --out_dir $out_dir --path_file $path_files --tissue_autoxcute_path $tissue_autoxcute_path --sample_autoxcute_path $sample_autoxcute_path --ROI $ROI --get_data_basis $get_data_basis --basis_ROI $basis_ROI
sparse_subspace.exe --out_dir $out_dir --path_file $path_files --estimate_basis $estimate_basis --n_basis_data $n_basis_data --basis_path $basis_path --r $r --lamb $lamb --mu $mu --max_iter $max_iter
python.exe process_data.py --out_dir $out_dir --path_file $path_files  --r $r --mz_range $mz_range